
language: cpp

cache: ccache


dist: trusty #14.04
sudo: false

jobs:
  include:
    ###
    - stage: linux, gcc, Qt5, Release
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - ccache
            - ninja-build
            - libpng-dev
            - libjpeg-dev
            - libopencv-dev

      before_install:
        # add external ppf for Qt 5.9
        - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
        - sudo apt-get -qy update

      install:
        - sudo apt-get -qy install qt59-meta-minimal
        
      script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        - ninja -j 3

    ###
    - stage: linux, gcc, Qt5, Debug
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - ccache
            - ninja-build
            - libpng-dev
            - libjpeg-dev
            - libopencv-dev

      before_install:
        # add external ppf for Qt 5.9
        - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
        - sudo apt-get -qy update

      install:
        - sudo apt-get -qy install qt59-meta-minimal
        
      script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
        - ninja -j 3

    ###
    - stage: linux, gcc-7.0, Qt5, Release
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - ccache
            - ninja-build
            - libpng-dev
            - libjpeg-dev
            - libopencv-dev
            - g++-7.0

      before_install:
        # add external ppf for Qt 5.9
        - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
        - sudo apt-get -qy update
        - eval "${MATRIX_EVAL}

      install:
        - sudo apt-get -qy install qt59-meta-minimal
        
      env:
        - MATRIX_EVAL="CC=gcc-7.0 && CXX=g++-7.0"

      script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        - ninja -j 3

    ###
    - stage: linux, clang-5.0, Qt5, Release
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - ccache
            - ninja-build
            - libpng-dev
            - libjpeg-dev
            - libopencv-dev
            - clang-5.0

      before_install:
        # add external ppf for Qt 5.9
        - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
        - sudo apt-get -qy update
        - eval "${MATRIX_EVAL}

      install:
        - sudo apt-get -qy install qt59-meta-minimal
        
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

      script:
        - mkdir build
        - cd build
        - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        - ninja -j 3

  #######################################################
  
    ###
    - stage: Mac OS, clang, Qt5 & OpenCV from brew, Release
      os: osx #uses OS X 10.11.6 & Xcode 7.3.1
      compiler: clang

      before_install:
        - brew update
        - brew outdated qt5 || brew upgrade qt5
        - brew outdated opencv || (brew tap homebrew/science && brew upgrade opencv)

      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make -j 3

    ###
    - stage: Mac OS, recent clang, Qt5 & OpenCV from brew, Release
      os: osx
      osx_image: xcode9.1  #OS X 10.12 & Xcode 9.1
      compiler: clang

      before_install:
        - brew update
        - brew outdated qt5 || brew upgrade qt5
        - brew outdated opencv || (brew tap homebrew/science && brew upgrade opencv)

      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make -j 3

        
       
        