#ifndef LIPSUM4QT_GLOBAL_H
#define LIPSUM4QT_GLOBAL_H

#include <QtCore/qglobal.h>

//#if defined(LIPSUM4QT_LIBRARY)
//#define LIPSUM4QTSHARED_EXPORT Q_DECL_EXPORT
//#else
//#define LIPSUM4QTSHARED_EXPORT Q_DECL_IMPORT
//#endif
#define LIPSUM4QTSHARED_EXPORT

#endif // LIPSUM4QT_GLOBAL_H
